### ISSUE TITLE
[PicoDrive] Stop screen after going to home screen

### ISSUE THREAD

**Issue by sprknd** [bubble2k16/emus3ds#23]
PicoDrive doesn't refreshing screen after going to home screen. After that, only sounds and controls are available, and the screen is freeze. I've tested several devices and firmware versions (New 3DS 11.9, New 3DS XL 9.99, New 3DS XL 11.9) and all devices are having same problem. I'm using B9S CFW.

**Comment by ObscureExtractor** [comment]
I have this issue too when backing out to the home menu when a Megadrive game is running. I don't know about you but when I back out to the home menu when the game is playing, the last sound it makes keeps playing infinitely until you press the home button again to go back in. This seems to be a hardware/dsp audio issue. Not that the dsp audio itself can't handle it, I think it's just a hardware issue with all variants of the 3ds and probably can't be fixed. Just try to manually exit from the emulator screen so the game won't freeze.
